title:             Clean Blog
email:             iflores.siaca@gmail.com
description:       A Blog Theme by Start Bootstrap
author:            Ian Flores Siaca
baseurl:           ""
url:               "https://ian-flores.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   ian-flores
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
