title:             Bayesian Politics
email:             iflores.siaca@gmail.com
description:       A Webpage about Data Science, Cyber Security and Politics
author:            Ian Flores Siaca
baseurl:           ""
url:               "https://ian-flores.github.io"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   ian-flores
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
